---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "mawo-helm.fullname" . }}
  labels:
    {{- include "mawo-helm.labels" $ | nindent 4 }}
rules:
  - verbs: ['get', 'list']
    apiGroups: ['']
    resources: ['namespaces']

  - verbs: ['*']
    apiGroups: ['']
    resources:
      - pods
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:  {{ include "mawo-helm.fullname" . }}
  labels:
    {{- include "mawo-helm.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name:  {{ include "mawo-helm.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "mawo-helm.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
