apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mawo-helm.serviceAccountName" . }}
  labels:
    {{- include "mawo-helm.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
