---
name: buildflow-release
on:
  push:
    branches:
      - main
    tags:
      - '*'

env:
  GO_VERSION: 1.18.1
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: print meta information
      run: |
        echo ${{ github.ref }}
        echo ${{ github.ACTOR }}
    - name: push the image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        tags: latest
        image: mawo
        registry: ghcr.io
        username: ${{ github.ACTOR }}
        password: ${{ secrets.PUSHTOKEN }}
