name: buildflow
on: [push]

env:
  GO_VERSION: 1.18.1
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  go-build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: make magic
        run: |
          make build-cli GIT_COMMIT=${{ github.sha }}
          make build-server GIT_COMMIT=${{ github.sha }}

  docker-build:
    if: github.ref != 'refs/heads/master' ## do not run on master
    runs-on: ubuntu-latest
    needs:
      - go-build
    steps:
    - uses: actions/checkout@v3
    - name: docker build
      run: make build-image GIT_COMMIT=${{ github.sha }}

  publish:
    runs-on: ubuntu-latest
    needs:
      - docker-build
    steps:
    - uses: actions/checkout@v3
    - name: print commit sha
      run: echo ${{ github.sha }}
    - name: push the image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        tag: ${{ github.GITHUB_REF }}
        image: la3mmchen/mawo
        registry: ghcr.io
        username: ${{ github.ACTOR }}
        password: ${{ secrets.PUSHTOKEN }}

  publish-latest:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - docker-build
    steps:
    - uses: actions/checkout@v3
    - name: print commit sha
      run: echo ${{ github.sha }}
    - name: push the image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        tag: lastest
        image: la3mmchen/mawo
        registry: ghcr.io
        username: ${{ github.ACTOR }}
        password: ${{ secrets.PUSHTOKEN }}
